
name: Integration

on:
  push

permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install flake8 pytest Pyqt6 pytest-qt
        sudo apt-get update
        sudo apt-get install -y libegl1
        if [ -f slitmaskgui/requirements.txt ]; then pip install -r slitmaskgui/requirements.txt; fi

    # - name: Lint with flake8
    #   run: |
    #     source .venv/bin/activate
    #     flake8 slitmaskgui/ --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.venv
    #     flake8 slitmaskgui/ --count --exit-zero --max-complexity=10 --statistics #--max-line-length=120 --exclude=.venv
        
    - name: Test
      run: |
        source .venv/bin/activate
        python3 -m pytest slitmaskgui/tests/
  #test:
